In [1]:
import numpy as np

In [72]:
a = np.array([np.random.randint(2) for _ in range(8)])
b = np.array([np.random.randint(2) for _ in range(8)])

In [73]:
print(a)
print(b)

[0 0 0 1 1 0 1 1]
[1 1 0 1 1 1 1 0]


In [92]:
a = np.array([1,0,1,0,1])
b = np.array([1,1,1,0,0])

In [93]:
n=len(a)
c=np.zeros(n)
#n=8
memory = False
for i in range(n):
    if memory==True:
        c[n-1-i]=a[n-1-i]+b[n-1-i]+1
    else:
        c[n-1-i]=a[n-1-i]+b[n-1-i]    
    if c[n-1-i]==2:
        c[n-1-i]=0
        memory = True
    elif c[n-1-i]==3:
        c[n-1-i]=1
        memory = True
    else:
        memory = False
    if (i == n-1) & (c[0]==1):
        print("i: ",i,"c: ",c,"memory:",memory)
        if memory == True:
            c= np.insert(c,0,1)

i:  4 c:  [1. 0. 0. 0. 1.] memory: True


In [94]:
print(a)
print(b)
print("-"*20)
print(np.array([int(x) for x in c]))

[1 0 1 0 1]
[1 1 1 0 0]
--------------------
[1 1 0 0 0 1]
