 - **Osman Dogukan Kefeli** 
 - *090170119*


Cholesky Decomposition

We're trying to write the Matrix
$A= \begin{bmatrix} 4 & 12 & -16 \\ 12 & 37 & -43 \\ -16 & -43 & 95 \end{bmatrix}$

as $LxL^T$

Elements of Matrices $L$ and $L^T$ can be written as

$L=\begin{bmatrix} l_{11} & 0 & 0 \\ l_{21} & l_{22} & 0 \\ l_{31} & l_{32} & l_{33} \end{bmatrix}$  <br /><br />      and <br /><br />
$L^T= \begin{bmatrix} l_{11} & l_{21} & l_{31} \\ 0 & l_{22} & l_{32} \\ 0 & 0 & l_{33} \end{bmatrix} $

By multiplying first row of $L$ and first column of $L^T$

${l_{11}}^2 = 4 $ , $l_{11}=2$

Continuing for other elements,

$l_{11}*l_{21}+0*l_{22} = 12$ $=>$ $l_{21}=6$  and so forth...

Generalized formula for elements is

\begin{eqnarray*}
l_{kk} &=& \sqrt{ a_{kk} - \sum^{k-1}_{j=1} l^2_{kj}}\\
l_{ik} &=& \frac{1}{l_{kk}} \left( a_{ik} - \sum^{k-1}_{j=1} l_{ij} l_{kj} \right), i > k
\end{eqnarray*}

Computing with Python3

In [1]:
from math import sqrt
import numpy as np
 
def cholesky(A):
    n = len(A)

    # Initiate a zero matrix for L
    L = np.zeros((n,n))


    for i in range(n):
        for k in range(i+1):
            tmp_sum = sum(L[i][j] * L[k][j] for j in range(k))
            
            if (i == k): # Diagonal elements
                L[i][k] = sqrt(A[i][i] - tmp_sum)
            else:
                L[i][k] = (1.0 / L[k][k] * (A[i][k] - tmp_sum))
    return L
 
A = np.array([[4, 12, -16],[12, 37, -43],[-16, -43, 98]])
L = cholesky(A)
print("A:");
print(A)
print("Lower triangular")
print(L)
print("Transpose of Lower triangular")
print(L.T)


A:
[[  4  12 -16]
 [ 12  37 -43]
 [-16 -43  98]]
Lower triangular
[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]
Transpose of Lower triangular
[[ 2.  6. -8.]
 [ 0.  1.  5.]
 [ 0.  0.  3.]]
