 - **Osman Dogukan Kefeli** 
 - *090170119*


## QR Algorithm

    QR algorithm or QR iteration is an eigenvalue algorithm: that is, a procedure to calculate the eigenvalues and eigenvectors of a matrix.

   For a square matrix $A$, QR Decomposition converts $A$ into the products of two matrices. <br>
An orthogonal matrix $Q$ and a upper triangular matrix $R$.

\begin{eqnarray*}
A = QR
\end{eqnarray*}

Let $A_0 :=A$ At the $k^{th}$ step we compute QR Decomposition $A_k=Q_kR_k$

$$A_{k+1}=R_kQ_k=Q_k^{-1}Q_kR_kQ_k=Q_k^{-1}A_kQ_k=Q_k^{T}A_kQ_k    $$

All the $A_k$ are similar hence they have same $eigenvalues$.

In [1]:
import numpy as np
A = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]])

In [2]:


def gs_m(A):

    m,n= A.shape
    A= A.copy()
    Q= np.zeros((m,n))
    R= np.zeros((n,n))

    for k in range(n):

        R[k,k]= np.linalg.norm(A[:,k:k+1].reshape(-1),2)
        Q[:,k:k+1]= A[:,k:k+1]/R[k,k]
        R[k:k+1,k+1:n+1]= np.dot( Q[:,k:k+1].T, A[:,k+1:n+1] )
        A[:,k+1:n+1]= A[:, k+1:n+1] - np.dot( Q[:,k:k+1], R[k:k+1,k+1:n+1])


    return Q, R
Q,R=gs_m(A)
A,Q,R

(array([[ 12, -51,   4],
        [  6, 167, -68],
        [ -4,  24, -41]]),
 array([[ 0.85714286, -0.39466607, -0.34174306],
        [ 0.42857143,  0.90372809,  0.        ],
        [-0.28571429,  0.16587414, -0.93979342]]),
 array([[ 14.        ,  21.        , -14.        ],
        [  0.        , 174.8313473 , -69.41546918],
        [  0.        ,   0.        ,  35.11409973]]))